# -*- coding: utf-8 -*-
"""avlanache_data_extract.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xVHtBHwPg5u_n9SkZ-mkwQbrGTGRftEO
"""

#from google.colab import drive
#drive.mount('/content/drive')

import pandas as pd
from regobslib import *
import datetime as dt
from ava_functions.Lists_and_Dictionaries.Paths import obs_path

#NotebookApp.iopub_data_rate_limit=1.0e10

START = dt.date(2016, 1, 1)
STOP = dt.date(2025, 8, 25)
#REGIONS = [SnowRegion.HARDANGER]

connection = Connection(prod=True)
varsom = connection.get_varsom(START, STOP)
# region = varsom.to_problem_csv()

problems = varsom.to_problem_frame(with_priorities=True)
problems.to_csv(f"{obs_path}/IMPETUS/Avalanches_Danger_Files/Avalanche_Problems_List.csv")


#%% store the list of mainland A regions
"""
a_regs_mainland = []
for reg in A_REGIONS_MAINLAND:
    a_regs_mainland.append(reg)
# end for reg

pd.Series(a_regs_mainland).to_csv(f"{obs_path}/IMPETUS/Avalanches_Danger_Files/A_Regs_Mainland.csv")

"""